const DELETE_TRACKS_REQUEST = 'DELETE_TRACKS_REQUEST';
const DELETE_TRACKS_FAILURE = 'DELETE_TRACKS_FAILURE';
const DELETE_TRACKS_SUCCESS = 'DELETE_TRACKS_SUCCESS';


export { DELETE_TRACKS_REQUEST, DELETE_TRACKS_FAILURE, DELETE_TRACKS_SUCCESS };
