const FETCH_TRACKS_REQUEST = 'FETCH_TRACKS_REQUEST';

const FETCH_TRACKS_FAILURE = 'FETCH_TRACKS_FAILURE';

const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';


export { FETCH_TRACKS_REQUEST, FETCH_TRACKS_FAILURE, FETCH_TRACKS_SUCCESS };
